### ISSUE TITLE
Launcher run after closing with X on Linux

### ISSUE THREAD

**Issue by BTCapsule** [LayerTwo-Labs/Electron-DC-Launcher#10]
If I open the launcher with a double click and use the X to close, it continues to run in the background. If I open the launcher from the console and use the X, I have to Ctrl+C to terminate it

![Image](https://github.com/user-attachments/assets/87a934b4-bd54-40ed-9dfe-dc11ca9e38be)

**Comment by BTCapsule** [comment]
This is also happening on Windows. I’m using the latest Windows update and closing with the X, but it keeps running as a Background Process

![Image](https://github.com/user-attachments/assets/86ca97a5-260c-46c5-9337-8df4fcdd17e7)

**Comment by seriouscatsoserious** [comment]
Thanks, fixed in latest.

**Comment by BTCapsule** [comment]
This works great on Linux, but I’m still having the issue on Windows. Whether I run it from the console or open straight from the app, it continues to run after I hit the X. This is the latest launcher on releases.
